fixtures:
  repositories:
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
    firewall: git://github.com/puppetlabs/puppetlabs-firewall.git
    apt: git://github.com/puppetlabs/puppetlabs-apt.git
  symlinks:
    postgresql: "#{source_dir}"
