---
language: ruby
bundler_args: --without development
script: fakeroot bundle exec rake spec SPEC_OPTS='--format documentation'
rvm:
- 1.8.7
- 1.9.3
- 2.0.0
env:
  matrix:
  - PUPPET_GEM_VERSION="~> 2.7.0"
  - PUPPET_GEM_VERSION="~> 3.2.0"
  - PUPPET_GEM_VERSION="~> 3.4.0"
  - PUPPET_GEM_VERSION="~> 3.5.0.rc3" STRICT_VARIABLES="yes"
matrix:
  fast_finish: true
  exclude:
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 2.7.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 2.7.0"
notifications:
  email: false
