name 'inkling-postgresql'
version '0.2.0'
source 'git://github.com/inkling/puppet-postgresql.git'
author 'Inkling'
description 'PostgreSQL defined resource types'
summary 'PostgreSQL defined resource types'
license 'Apache'
project_page 'https://github.com/inkling/puppet-postgresql'

dependency 'puppetlabs/stdlib', '>= 2.4.0'
dependency 'puppetlabs/firewall', '>= 0.0.4'
