name 'puppetlabs-postgresql'
version '2.0.1'
source 'git://github.com/puppetlabs/puppet-postgresql.git'
author 'Inkling/Puppet Labs'
description 'PostgreSQL defined resource types'
summary 'PostgreSQL defined resource types'
license 'Apache'
project_page 'https://github.com/puppetlabs/puppet-postgresql/issues'

dependency 'puppetlabs/stdlib', '>=3.2.0 <4.0.0'
dependency 'puppetlabs/firewall', '>= 0.0.4'
dependency 'puppetlabs/apt', '>=1.1.0 <2.0.0'
