name 'puppetlabs-postgresql'
version '1.0.0'
source 'git://github.com/puppetlabs/puppet-postgresql.git'
author 'Inkling/Puppet Labs'
description 'PostgreSQL defined resource types'
summary 'PostgreSQL defined resource types'
license 'Apache'
project_page 'https://github.com/puppetlabs/puppet-postgresql/issues'

dependency 'puppetlabs/stdlib', '2.x'
dependency 'puppetlabs/firewall', '>= 0.0.4'
