# -*- mode: ruby -*-
# vi: set ft=ruby :

# puppet-postgresql
# For all details and documentation:
# http://github.com/inkling/puppet-postgresql
#
# Copyright 2012- Inkling Systems, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

Vagrant::Config.run do |config|

  # Test on 64 bit lucid
  config.vm.box = "lucid64"
  config.vm.box_url = "http://files.vagrantup.com/lucid64.box"

  # Resolve DNS via NAT
  config.vm.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]

  # Share the stdlib module
  #  TODO: it would be better to install this via the puppet module tool
  config.vm.share_folder "puppetlabs-stdlib-module", "/usr/share/puppet/modules/stdlib", "../../puppetlabs-stdlib"

  # Share the postgressql module
  config.vm.share_folder "puppet-postgresql-module", "/usr/share/puppet/modules/postgresql", ".."

  # Share the module of test classes
  config.vm.share_folder "puppet-postgresql-tests", "/usr/share/puppet/modules/postgresql_tests", "."

  # Provision with a base puppet config just so we don't have to repeat the puppet user/group
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "."
    puppet.manifest_file  = "base.pp"
  end
end
